name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload test report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Send test report via email
        if: always()
        run: |
          npm install nodemailer
          
          # Create the email sending script
          echo "const nodemailer = require('nodemailer');" > sendEmail.js
          echo "const fs = require('fs');" >> sendEmail.js
          echo "const transporter = nodemailer.createTransport({" >> sendEmail.js
          echo "  service: 'gmail'," >> sendEmail.js
          echo "  auth: {" >> sendEmail.js
          echo "    user: process.env.EMAIL_USER," >> sendEmail.js
          echo "    pass: process.env.EMAIL_PASS" >> sendEmail.js
          echo "  }" >> sendEmail.js
          echo "});" >> sendEmail.js
          echo "const mailOptions = {" >> sendEmail.js
          echo "  from: process.env.EMAIL_USER," >> sendEmail.js
          echo "  to: process.env.RECIPIENT_EMAIL," >> sendEmail.js
          echo "  subject: 'Playwright Test Execution Report'," >> sendEmail.js
          echo "  text: 'Please find the attached Playwright test execution report.'," >> sendEmail.js
          echo "  attachments: [{" >> sendEmail.js
          echo "    filename: 'playwright-report.zip'," >> sendEmail.js
          echo "    path: './playwright-report.zip'" >> sendEmail.js
          echo "  }]" >> sendEmail.js
          echo "};" >> sendEmail.js
          echo "transporter.sendMail(mailOptions, (error, info) => {" >> sendEmail.js
          echo "  if (error) {" >> sendEmail.js
          echo "    console.log('Error:', error);" >> sendEmail.js
          echo "  } else {" >> sendEmail.js
          echo "    console.log('Email sent: ' + info.response);" >> sendEmail.js
          echo "  }" >> sendEmail.js
          echo "});" >> sendEmail.js

          # Zip the report folder
          zip -r playwright-report.zip playwright-report

          # Run the email script using Node.js
          node sendEmail.js

        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
